 
 /*------------------------------------------------------------------------
    File        : customerdata
    Purpose     : 
    Syntax      : 
    Description : 
    Author(s)   : nm01
    Created     : Fri Mar 20 12:41:54 ADT 2020
    Notes       : 
  ----------------------------------------------------------------------*/

USING Progress.Lang.*.

BLOCK-LEVEL ON ERROR UNDO, THROW.

CLASS customerdata: 

END CLASS.